import { chromium } from "playwright-core";
import { startServer, stopServer, launchOptions } from "./helpers.mjs";
await startServer();
const B = `http://localhost:${process.env.E2E_PORT || 3111}`; let pass = 0, fail = 0; const ok = (n, c, x = "") => { c ? pass++ : fail++; console.log(c ? "✔" : "✘", n, x); };
const b = await chromium.launch(launchOptions());
const p = await (await b.newContext({ viewport: { width: 420, height: 900 } })).newPage();
const errs = []; p.on("pageerror", e => errs.push(e.message));
await p.goto(B + "/child"); await p.waitForSelector("text=오늘 연습");
ok("기본은 한국어", await p.locator("text=오늘 연습").count() === 1);
await p.getByRole("button", { name: "화면 설정" }).click(); await p.getByRole("button", { name: "English" }).click();
await p.waitForSelector("text=Today's practice");
ok("English: 홈 문구", (await p.locator("body").innerText()).includes("Hi, 예시 아동!") || (await p.locator("body").innerText()).includes("Ready to listen"));
ok("English: 콘텐츠 안내(이야기는 한국어)", await p.locator("text=in Korean for now").count() === 1);
ok("English: 설정 패널도 영어", await p.locator("text=Display settings").count() >= 1 && await p.locator("text=Read aloud").count() === 1);
await p.locator("a:has-text('Start')").first().click(); await p.waitForSelector("text=I watched it");
const body = await p.locator("main").innerText();
ok("English: 보기 화면 문구", body.includes("Your friend says") && body.includes("Listen again"));
ok("English: 화면 문구에 한글 UI 문구가 없다(이야기 본문 제외)", !/친구가 말해요|다시 듣기|다 봤어요/.test(body));
await p.getByRole("button", { name: /I watched it/ }).click(); await p.waitForSelector("text=Which reply makes your friend feel better?");
await p.locator("main button.text-left").first().click(); await p.getByRole("button", { name: /Let's practice/ }).click();
await p.waitForSelector("text=/Your friend says · 1\\/3/");
ok("English: 연습 화면(방법·번호)", await p.getByRole("tab", { name: "Choose" }).count() === 1 && await p.getByRole("tab", { name: "Write" }).count() === 1);
await p.locator("main button.text-left").first().click(); await p.waitForSelector("[role=status]");
await p.getByRole("button", { name: /Try once more/ }).click(); await p.locator("main button.text-left").first().click(); await p.waitForSelector("[role=status]");
await p.getByRole("button", { name: /See mission/ }).click(); await p.waitForSelector("text=Today's mission");
ok("English: 미션 화면", (await p.locator("main").innerText()).includes("you get 5 stickers"));
ok("English: 'Practice sticker +1'", await p.locator("text=Practice sticker +1").count() === 1);
await p.goto(B + "/child/stickers"); await p.waitForSelector("text=/My stickers/");
ok("English: 스티커판", (await p.locator("h1").innerText()).includes("My stickers (1)"));
await p.reload(); await p.waitForSelector("text=/My stickers/"); ok("새로고침해도 언어 유지", true);
await p.goto(B + "/child"); await p.getByRole("button", { name: "Display settings" }).click(); await p.getByRole("button", { name: "한국어" }).click();
await p.waitForSelector("text=오늘 연습"); ok("한국어로 되돌리기", true);
ok("JS 오류 없음", errs.length === 0, errs.join("|"));
console.log(`\n통과 ${pass} / 실패 ${fail}`); await b.close(); await stopServer(); process.exit(fail ? 1 : 0);
